### ISSUE TITLE
Cannot compile driver on 1st gen Raspberry pi

### ISSUE THREAD

**Issue by VirtualTim** [amnezia-vpn/amneziawg-linux-kernel-module#121]
Hi, I just ran into an issue building this for a 1st gen Raspberry pi. This was working previously (last week), but I foolishly had unattended-upgrades enabled, and now I can't load the driver after a restart.

From: `sudo apt install -f`:
```
make -j1 KERNELRELEASE=6.12.47+rpt-rpi-v7l -C /var/lib/dkms/amneziawg/1.0.0/build......................(bad exit status: 2)
Error! Bad return status for module build on kernel: 6.12.47+rpt-rpi-v7l (armv6l)
Consult /var/lib/dkms/amneziawg/1.0.0/build/make.log for more information.
Error! One or more modules failed to install during autoinstall.
Refer to previous errors for more information.
dkms: autoinstall for kernel: 6.12.47+rpt-rpi-v7l failed!
run-parts: /etc/kernel/postinst.d/dkms exited with return code 11
dpkg: error processing package linux-image-6.12.47+rpt-rpi-v7l (--configure):
 installed linux-image-6.12.47+rpt-rpi-v7l package post-installation script subprocess returned error exit status 1
dpkg: dependency problems prevent configuration of linux-headers-6.12.47+rpt-rpi-v6:
 linux-headers-6.12.47+rpt-rpi-v6 depends on linux-image-6.12.47+rpt-rpi-v6 (= 1:6.12.47-1+rpt1~bookworm) | linux-image-6.12.47+rpt-rpi-v6-unsigned (= 1:6.12.47-1+rpt1~bookworm); however:
  Package linux-image-6.12.47+rpt-rpi-v6 is not configured yet.
  Package linux-image-6.12.47+rpt-rpi-v6-unsigned is not installed.
```

From `/var/lib/dkms/amneziawg/1.0.0/build/make.log`:
```
patching file netlink.c
  CC [M]  /var/lib/dkms/amneziawg/1.0.0/build/generated/main.o
In file included from /var/lib/dkms/amneziawg/1.0.0/build/generated/main.c:12:
/var/lib/dkms/amneziawg/1.0.0/build/generated/uapi/wireguard.h:156:22: error: expected declaration specifiers or ‘...’ before string constant
  156 | #define WG_GENL_NAME "amneziawg"
      |                      ^~~~~~~~~~~
/var/lib/dkms/amneziawg/1.0.0/build/generated/main.c:79:26: note: in expansion of macro ‘WG_GENL_NAME’
   79 | MODULE_ALIAS_GENL_FAMILY(WG_GENL_NAME);
      |                          ^~~~~~~~~~~~
make[2]: *** [/usr/src/linux-headers-6.12.47+rpt-common-rpi/scripts/Makefile.build:249: /var/lib/dkms/amneziawg/1.0.0/build/generated/main.o] Error 1
make[1]: *** [/usr/src/linux-headers-6.12.47+rpt-common-rpi/Makefile:1970: /var/lib/dkms/amneziawg/1.0.0/build/generated] Error 2
make: *** [Makefile:94: module] Error 2
make: Leaving directory '/var/lib/dkms/amneziawg/1.0.0/build'
```
