### ISSUE TITLE
Failed to compile on Ubuntu 22.04

### ISSUE THREAD

**Issue by ktopofi-stack** [amnezia-vpn/amneziawg-linux-kernel-module#111]
/var/crash# less amneziawg-dkms.0.crash

ProblemType: Package
DKMSBuildLog:
 DKMS make.log for amneziawg-1.0.0 for kernel 5.15.0-160-generic (x86_64)
 Sat Oct 18 03:35:50 UTC 2025
 make: Entering directory '/usr/src/linux-headers-5.15.0-160-generic'
   CC [M]  /var/lib/dkms/amneziawg/1.0.0/build/main.o
 In file included from <command-line>:
 /var/lib/dkms/amneziawg/1.0.0/build/compat/compat.h:1147:47: warning: ‘struct dst_cache’ declared inside parameter list will not be visible outside of this definition or declaration
  1147 | static inline void dst_cache_reset_now(struct dst_cache *dst_cache)
       |                                               ^~~~~~~~~
 /var/lib/dkms/amneziawg/1.0.0/build/compat/compat.h: In function ‘dst_cache_reset_now’:
 /var/lib/dkms/amneziawg/1.0.0/build/compat/compat.h:1151:23: error: invalid use of undefined type ‘struct dst_cache’
  1151 |         if (!dst_cache->cache)
       |                       ^~
 /var/lib/dkms/amneziawg/1.0.0/build/compat/compat.h:1154:18: error: invalid use of undefined type ‘struct dst_cache’
  1154 |         dst_cache->reset_ts = jiffies;
       |                  ^~
 /var/lib/dkms/amneziawg/1.0.0/build/compat/compat.h:1154:31: error: ‘jiffies’ undeclared (first use in this function)
  1154 |         dst_cache->reset_ts = jiffies;
       |                               ^~~~~~~
 /var/lib/dkms/amneziawg/1.0.0/build/compat/compat.h:1154:31: note: each undeclared identifier is reported only once for each function it appears in
 /var/lib/dkms/amneziawg/1.0.0/build/compat/compat.h:1155:9: error: implicit declaration of function ‘for_each_possible_cpu’ [-Werror=implicit-function-declaration]
  1155 |         for_each_possible_cpu(i) {
       |         ^~~~~~~~~~~~~~~~~~~~~
 /var/lib/dkms/amneziawg/1.0.0/build/compat/compat.h:1155:33: error: expected ‘;’ before ‘{’ token
  1155 |         for_each_possible_cpu(i) {
       |                                 ^~
       |                                 ;
 In file included from <command-line>:
 /var/lib/dkms/amneziawg/1.0.0/build/compat/compat.h: At top level:
 /var/lib/dkms/amneziawg/1.0.0/build/compat/compat.h:1286:19: error: static declaration of ‘timer_delete’ follows non-static declaration
  1286 | static inline int timer_delete(struct timer_list *timer)
       |                   ^~~~~~~~~~~~
 In file included from /var/lib/dkms/amneziawg/1.0.0/build/compat/compat.h:1285,
                  from <command-line>:
 ./include/linux/timer.h:186:12: note: previous declaration of ‘timer_delete’ with type ‘int(struct timer_list *)’
   186 | extern int timer_delete(struct timer_list *timer);
       |            ^~~~~~~~~~~~
 In file included from ./include/net/ip_tunnels.h:19,
                  from ./include/net/udp_tunnel.h:5,
                  from /var/lib/dkms/amneziawg/1.0.0/build/compat/compat.h:1297,
                  from <command-line>:
 ./include/net/dst_cache.h:91:6: error: conflicting types for ‘dst_cache_reset_now’; have ‘void(struct dst_cache *)’
    91 | void dst_cache_reset_now(struct dst_cache *dst_cache);
       |      ^~~~~~~~~~~~~~~~~~~
 In file included from <command-line>:
 /var/lib/dkms/amneziawg/1.0.0/build/compat/compat.h:1147:20: note: previous definition of ‘dst_cache_reset_now’ with type ‘void(struct dst_cache *)’
  1147 | static inline void dst_cache_reset_now(struct dst_cache *dst_cache)
       |                    ^~~~~~~~~~~~~~~~~~~
 cc1: some warnings being treated as errors
 make[1]: *** [scripts/Makefile.build:297: /var/lib/dkms/amneziawg/1.0.0/build/main.o] Error 1
 make: *** [Makefile:1930: /var/lib/dkms/amneziawg/1.0.0/build] Error 2
 make: Leaving directory '/usr/src/linux-headers-5.15.0-160-generic'
DKMSKernelVersion: 5.15.0-160-generic
Date: Sat Oct 18 03:35:54 2025
DuplicateSignature: dkms:amneziawg-dkms:1.0.0-0~202510180146+eaffd2b~ubuntu22.04.1:/var/lib/dkms/amneziawg/1.0.0/build/compat/compat.h:1151:23: error: invalid use of undefined type ‘struct dst_cache’
Package: amneziawg-dkms 1.0.0-0~202510180146+eaffd2b~ubuntu22.04.1
PackageVersion: 1.0.0-0~202510180146+eaffd2b~ubuntu22.04.1
SourcePackage: amneziawg-linux-kmod
Title: amneziawg-dkms 1.0.0-0~202510180146+eaffd2b~ubuntu22.04.1: amneziawg kernel module failed to build

**Comment by ygurov** [comment]
fixed in #113
