### ISSUE TITLE
doesn't build for the 5.15.0-160-generic kernel

### ISSUE THREAD

**Issue by absolutelynothelix** [amnezia-vpn/amneziawg-linux-kernel-module#108]
```
legacy:~# apt install -y amneziawg
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
amneziawg is already the newest version (1.0.20210914-0~202509032017+5c6ffd6~ubuntu22.04.1).
0 upgraded, 0 newly installed, 0 to remove and 8 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up amneziawg-dkms (1.0.0-0~202510170157+931ffad~ubuntu22.04.1) ...
Removing old amneziawg-1.0.0 DKMS files...
Deleting module amneziawg-1.0.0 completely from the DKMS tree.
Loading new amneziawg-1.0.0 DKMS files...
Building for 5.15.0-160-generic
Building initial module for 5.15.0-160-generic
ERROR: Cannot create report: [Errno 17] File exists: '/var/crash/amneziawg-dkms.0.crash'
Error! Bad return status for module build on kernel: 5.15.0-160-generic (x86_64)
Consult /var/lib/dkms/amneziawg/1.0.0/build/make.log for more information.
dpkg: error processing package amneziawg-dkms (--configure):
 installed amneziawg-dkms package post-installation script subprocess returned error exit status 10
Errors were encountered while processing:
 amneziawg-dkms
needrestart is being skipped since dpkg has failed
E: Sub-process /usr/bin/dpkg returned an error code (1)
legacy:~# cat /var/lib/dkms/amneziawg/1.0.0/build/make.log
DKMS make.log for amneziawg-1.0.0 for kernel 5.15.0-160-generic (x86_64)
Fri Oct 17 04:15:54 PM MSK 2025
make: Entering directory '/usr/src/linux-headers-5.15.0-160-generic'
  CC [M]  /var/lib/dkms/amneziawg/1.0.0/build/main.o
In file included from <command-line>:
/var/lib/dkms/amneziawg/1.0.0/build/compat/compat.h:1282:19: error: static declaration of ‘timer_delete’ follows non-static declaration
 1282 | static inline int timer_delete(struct timer_list *timer)
      |                   ^~~~~~~~~~~~
In file included from /var/lib/dkms/amneziawg/1.0.0/build/compat/compat.h:1281,
                 from <command-line>:
./include/linux/timer.h:186:12: note: previous declaration of ‘timer_delete’ with type ‘int(struct timer_list *)’
  186 | extern int timer_delete(struct timer_list *timer);
      |            ^~~~~~~~~~~~
make[1]: *** [scripts/Makefile.build:297: /var/lib/dkms/amneziawg/1.0.0/build/main.o] Error 1
make: *** [Makefile:1930: /var/lib/dkms/amneziawg/1.0.0/build] Error 2
make: Leaving directory '/usr/src/linux-headers-5.15.0-160-generic'
legacy:~# uname -a
Linux legacy 5.15.0-160-generic #170-Ubuntu SMP Wed Oct 1 10:06:56 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux
legacy:~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.5 LTS
Release:        22.04
Codename:       jammy
```

**Comment by ygurov** [comment]
fixed in #113
